In [1]:
# Load  libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot
from pandas.plotting import scatter_matrix
from sklearn.preprocessing import LabelEncoder
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report


In [2]:
df=pd.read_csv("sample_user_data.csv") # Load data file



In [3]:
df1 = df.drop(["Date"], axis=1) # drop date column

In [4]:
count = df1.isna().sum() #find null values
print(count)

fullVisitorId                   0
VisitNumber                     0
VisitStartTime                  0
bounces                    232261
pageviews                      52
timeOnSite                 232827
totalTransactionRevenue    458131
transactions               458131
source                          0
medium                          0
campaign                        0
deviceCategory                  0
operatingSystem                 0
mobileDeviceModel               0
city                            0
ChannelGrouping                 0
dtype: int64


In [5]:
#fill null values
l_na=['bounces', 'pageviews', 'timeOnSite']
for column in l_na:
    df1[column].fillna(df1[column].mode()[0], inplace=True)

In [6]:
count = df1.isna().sum()
print(count)

fullVisitorId                   0
VisitNumber                     0
VisitStartTime                  0
bounces                         0
pageviews                       0
timeOnSite                      0
totalTransactionRevenue    458131
transactions               458131
source                          0
medium                          0
campaign                        0
deviceCategory                  0
operatingSystem                 0
mobileDeviceModel               0
city                            0
ChannelGrouping                 0
dtype: int64


In [7]:
df1.dtypes #data types

fullVisitorId              float64
VisitNumber                  int64
VisitStartTime               int64
bounces                    float64
pageviews                  float64
timeOnSite                 float64
totalTransactionRevenue    float64
transactions               float64
source                      object
medium                      object
campaign                    object
deviceCategory              object
operatingSystem             object
mobileDeviceModel           object
city                        object
ChannelGrouping             object
dtype: object

In [8]:
#to find uniques in columns
print("source\n", df1.source.unique())
print("\n medium \n", df1.medium.unique())
print(" \n campaign \n", df1.campaign.unique())
print(" \n deviceCategory \n", df1.deviceCategory.unique())
print(" \n operatingSystem \n", df1.operatingSystem.unique())
print(" \n mobileDeviceModel \n", df1.mobileDeviceModel.unique())
print(" \n city \n", df1.city.unique())
print(" \n ChannelGrouping \n", df1.ChannelGrouping.unique())



source
 ['google' 'bing' 'duckduckgo.com' '(direct)' 'docs.google.com'
 'siliconvalley.about.com' 'baidu' 'yahoo' 'm.baidu.com' 'Partners'
 'google.de' 'analytics.google.com' 'google.co.jp' 'google.com'
 'qiita.com' 'connect.googleforwork.com' 'google.co.uk' 'dfa' 'google.lk'
 '(not set)' 'googleads.g.doubleclick.net' 's0.2mdn.net' 'flipboard.com'
 'sites.google.com' 'feedly.com' 'int.search.tb.ask.com' 'mail.google.com'
 'chat.google.com' 'uk.businessinsider.com' 'businessinsider.com'
 'markets.businessinsider.com' 'businessinsider.in' 'hangouts.google.com'
 'newsstand.google.com' 'blog.golang.org' 'adwords.google.com'
 'finance.yahoo.com' 'github.com' 'yahoo.com' 'youtube.com' 'quora.com'
 'lm.facebook.com' 'reddit.com' 'm.facebook.com' 'l.facebook.com' 't.co'
 'groups.google.com' 'facebook.com' 'pinterest.com' 'search.mysearch.com'
 'phandroid.com' 'sashihara.jp' 'images.google' 'gophergala.com'
 'plus.google.com' 'm.reddit.com' 'm.youtube.com' 'au.search.yahoo.com'
 'msn.com' 'goog

In [9]:
len(df['transactions']) # length of the transactions

464439

In [10]:

# Binary encoding for transactions
for i in range(len(df['transactions'])):
    if pd.isnull(df['transactions'][i]):
        df1['transactions'][i]=0
    else:
        df1['transactions'][i]=1
        
df1.transactions.astype(int)

<ipython-input-10-311a9e07c5fe>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['transactions'][i]=0
<ipython-input-10-311a9e07c5fe>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['transactions'][i]=1


0         0
1         0
2         0
3         0
4         0
         ..
464434    0
464435    0
464436    0
464437    0
464438    0
Name: transactions, Length: 464439, dtype: int32

In [11]:
df1['transactions'] = df1.transactions.astype(int) # convert datatype to int 
df1.head()

fullVisitorId  VisitNumber  VisitStartTime  bounces  pageviews  timeOnSite  \
0   7.850780e+17            1      1493331229      1.0        1.0        10.0   
1   1.421020e+17            1      1493316667      1.0        1.0        10.0   
2   1.015860e+18            1      1493295075      1.0        1.0        10.0   
3   7.452650e+18            1      1493299324      1.0        1.0        10.0   
4   1.985240e+18            3      1493309497      1.0        1.0        10.0   

   totalTransactionRevenue  transactions  source   medium   campaign  \
0                      NaN             0  google  organic  (not set)   
1                      NaN             0  google  organic  (not set)   
2                      NaN             0  google  organic  (not set)   
3                      NaN             0  google  organic  (not set)   
4                      NaN             0  google  organic  (not set)   

  deviceCategory operatingSystem              mobileDeviceModel  \
0        desktop       Macintosh  not available in demo dataset   
1        desktop       Macintosh  not available in demo dataset   
2        desktop         Windows  not available in demo dataset   
3        desktop         Windows  not available in demo dataset   
4        desktop         Windows  not available in demo dataset   

                            city ChannelGrouping  
0                  Mountain View  Organic Search  
1  not available in demo dataset  Organic Search  
2  not available in demo dataset  Organic Search  
3  not available in demo dataset  Organic Search  
4  not available in demo dataset  Organic Search

In [12]:
df1.dtypes

fullVisitorId              float64
VisitNumber                  int64
VisitStartTime               int64
bounces                    float64
pageviews                  float64
timeOnSite                 float64
totalTransactionRevenue    float64
transactions                 int32
source                      object
medium                      object
campaign                    object
deviceCategory              object
operatingSystem             object
mobileDeviceModel           object
city                        object
ChannelGrouping             object
dtype: object

In [13]:
df1.transactions.unique()

array([0, 1])

In [14]:
# drop  mobileDeviceModel as it contains only one value
df1 = df1.drop(['mobileDeviceModel'], axis=1)


devicecategory = pd.get_dummies(df1['deviceCategory'], drop_first=True)

df1 = pd.concat([df1, devicecategory], axis=1)
del df1['deviceCategory']

In [15]:
df1.head(50)

fullVisitorId  VisitNumber  VisitStartTime  bounces  pageviews  \
0    7.850780e+17            1      1493331229      1.0        1.0   
1    1.421020e+17            1      1493316667      1.0        1.0   
2    1.015860e+18            1      1493295075      1.0        1.0   
3    7.452650e+18            1      1493299324      1.0        1.0   
4    1.985240e+18            3      1493309497      1.0        1.0   
5    5.904170e+18            1      1493343382      1.0        1.0   
6    7.275650e+18            1      1493311065      1.0        1.0   
7    8.767990e+17            1      1493326789      1.0        1.0   
8    2.458900e+18            3      1493362614      1.0        1.0   
9    9.745140e+18            1      1493284841      1.0        1.0   
10   1.917800e+17            1      1493306347      1.0        1.0   
11   6.568450e+18            1      1493300419      1.0        1.0   
12   6.397380e+18            2      1493309416      1.0        1.0   
13   2.457850e+18            3      1493297940      1.0        1.0   
14   4.095800e+18            3      1493296653      1.0        1.0   
15   9.353990e+18            1      1493302081      1.0        1.0   
16   7.250230e+18            1      1493314542      1.0        1.0   
17   4.195080e+18            1      1493305934      1.0        1.0   
18   8.256800e+18            1      1493345585      1.0        1.0   
19   4.359250e+18            1      1493346382      1.0        1.0   
20   1.244770e+18            1      1493320320      1.0        1.0   
21   1.859590e+18            1      1493304050      1.0        1.0   
22   7.292970e+17            1      1493290090      1.0        1.0   
23   1.762690e+18            1      1493299499      1.0        1.0   
24   2.939160e+18            2      1493335507      1.0        1.0   
25   7.454780e+18            1      1493299328      1.0        1.0   
26   3.424860e+18            1      1493297249      1.0        1.0   
27   4.317170e+18            1      1493288231      1.0        1.0   
28   4.452350e+18            1      1493325668      1.0        1.0   
29   9.551390e+18            1      1493361399      1.0        1.0   
30   6.018780e+18           96      1493355956      1.0        1.0   
31   4.843300e+18            1      1493303529      1.0        1.0   
32   7.900060e+18            3      1493324163      1.0        1.0   
33   4.010630e+18            1      1493351274      1.0        1.0   
34   3.496540e+18            3      1493318365      1.0        1.0   
35   2.273060e+18            1      1493297109      1.0        1.0   
36   1.151710e+17            1      1493278854      1.0        1.0   
37   2.172380e+18            1      1493327056      1.0        1.0   
38   1.119800e+18            1      1493315026      1.0        1.0   
39   3.858880e+18            1      1493331626      1.0        1.0   
40   7.964340e+18            1      1493299708      1.0        1.0   
41   3.267020e+17            1      1493279547      1.0        1.0   
42   9.209570e+18            1      1493295317      1.0        1.0   
43   7.972430e+18            1      1493301803      1.0        1.0   
44   1.078590e+18            1      1493361104      1.0        1.0   
45   4.437270e+18            1      1493298259      1.0        1.0   
46   8.946980e+18            1      1493337645      1.0        1.0   
47   6.525320e+18            1      1493276657      1.0        1.0   
48   8.716720e+18            1      1493287454      1.0        1.0   
49   3.199560e+17            1      1493331975      1.0        1.0   

    timeOnSite  totalTransactionRevenue  transactions          source  \
0         10.0                      NaN             0          google   
1         10.0                      NaN             0          google   
2         10.0                      NaN             0          google   
3         10.0                      NaN             0          google   
4         10.0                      NaN             0          googl

In [1]:
# Spiliting dependent and independent variables
dfx = df1.drop(['fullVisitorId', 'VisitNumber', 'VisitStartTime', 'totalTransactionRevenue', 'transactions'], axis=1)
dfx.head()

x = dfx.iloc[:,:].values
y = df1.iloc[:, 7].values

NameError: name 'df1' is not defined

In [17]:
print(y)

[0 0 0 ... 0 0 0]


In [18]:
dfx.dtypes

bounces            float64
pageviews          float64
timeOnSite         float64
source              object
medium              object
campaign            object
operatingSystem     object
city                object
ChannelGrouping     object
mobile               uint8
tablet               uint8
dtype: object

In [19]:
#Label Encoding independent variables
le = LabelEncoder()
x[:,3] = le.fit_transform(x[:,3])
x[:,4] = le.fit_transform(x[:,4])
x[:,5] = le.fit_transform(x[:,5])
x[:,6] = le.fit_transform(x[:,6])
x[:,7] = le.fit_transform(x[:,7])
x[:,8] = le.fit_transform(x[:,8])

In [20]:
x = x.astype(int)
y = y.astype(int)

In [21]:
print(y)

[0 0 0 ... 0 0 0]


In [22]:
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split # Import train_test_split function

# split into train test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(311174, 11) (153265, 11) (311174,) (153265,)


In [23]:
## Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf=clf.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [24]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.980921932600398


# MODEL PREDICTIONS

In [25]:
print(y_test)

[0 0 0 ... 0 0 0]


In [26]:
print(y_pred)

[0 0 0 ... 0 0 0]


Save predicted model

In [27]:
import pickle

In [28]:
with open('clf_pickle','wb') as f:
    pickle.dump(clf,f)